# Generated by Django 4.0.6 on 2022-08-19 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0002_combo_question_answer_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo_template',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_combo', to=settings.AUTH_USER_MODEL),
        ),
    ]
