# Generated by Django 4.0.6 on 2022-08-25 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating_app', '0003_alter_combo_template_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='puzzles_solved',
        ),
        migrations.AlterField(
            model_name='combo_instance',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combos_accessed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
